//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.0
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCResourceLibs {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class vsresources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal vsresources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RCResourceLibs.vsresources", typeof(vsresources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:my=&quot;clr-namespace:RCResourceLibs;assembly=RCResourceLibs&quot;&gt;
        ///    &lt;Style TargetType=&quot;{x:Type ContentControl}&quot;&gt;
        ///        &lt;Setter Property=&quot;Width&quot; Value=&quot;auto&quot; /&gt;
        ///        &lt;Setter Property=&quot;Height&quot; Value=&quot;auto&quot; /&gt;
        ///        &lt;Setter Property=&quot;HorizontalAlignment&quot; Value=&quot;Center&quot; /&gt;
        ///        &lt;Setter Property=&quot;VerticalAlignment&quot; V [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap compass {
            get {
                object obj = ResourceManager.GetObject("compass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        ///    &lt;Style TargetType=&quot;{x:Type ContentControl}&quot;&gt;
        ///        &lt;Setter Property=&quot;Width&quot; Value=&quot;350&quot; /&gt;
        ///        &lt;Setter Property=&quot;Height&quot; Value=&quot;150&quot; /&gt;
        ///        &lt;Setter Property=&quot;HorizontalAlignment&quot; Value=&quot;Left&quot; /&gt;
        ///        &lt;Setter Property=&quot;VerticalAlignment&quot; Value=&quot;Top&quot; /&gt;
        ///        &lt;Setter Property=&quot;Template&quot;&gt;
        ///            &lt;Setter.Value&gt;
        ///                &lt;ControlTempl [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string connector {
            get {
                return ResourceManager.GetString("connector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ResourceDictionary
        ///    xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        ///    &lt;Style x:Key=&quot;MWindowStyleChrome&quot; TargetType=&quot;{x:Type Window}&quot;&gt;
        ///        &lt;Setter Property=&quot;WindowStyle&quot; Value=&quot;None&quot;/&gt;
        ///        &lt;Setter Property=&quot;AllowsTransparency&quot; Value=&quot;True&quot;/&gt;
        ///        &lt;Setter Property=&quot;Background&quot; Value=&quot;Transparent&quot;/&gt;
        ///        &lt;!--&lt;Setter Property=&quot;MinHeight&quot; Value=&quot;600&quot;/&gt;--&gt;
        ///        &lt;!--&lt;Setter Property=&quot;MinWidth&quot; Value=&quot;800&quot;/&gt; [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string mainstylelib {
            get {
                return ResourceManager.GetString("mainstylelib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Windows;
        ///using System.Windows.Controls;
        ///using System.Windows.Data;
        ///using System.Windows.Documents;
        ///using System.Windows.Input;
        ///using System.Windows.Media;
        ///using System.Windows.Media.Imaging;
        ///using System.Windows.Navigation;
        ///using System.Windows.Shapes;
        ///
        ///namespace RCResourceLibs.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Логика взаимодействия для MainStyleLibrary.xaml        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string mainstylelib_xaml {
            get {
                return ResourceManager.GetString("mainstylelib_xaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ResourceDictionary
        ///	xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///	xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///&gt;
        ///    &lt;LinearGradientBrush x:Key=&quot;MenuItemSelectionFill&quot; EndPoint=&quot;0,1&quot; StartPoint=&quot;0,0&quot;&gt;
        ///        &lt;GradientStop Color=&quot;#34C5EBFF&quot; Offset=&quot;0&quot;/&gt;
        ///        &lt;GradientStop Color=&quot;#3481D8FF&quot; Offset=&quot;1&quot;/&gt;
        ///    &lt;/LinearGradientBrush&gt;
        ///    &lt;Geometry x:Key=&quot;Checkmark&quot;&gt;M 0,5.1 L 1.7,5.2 L 3.4,7.1 L 8,0.4 L 9.2,0 L 3.3,10.8 Z&lt;/Geometry&gt;
        ///    &lt;ControlTemplate x:Key=&quot;{Componen [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string menu_style {
            get {
                return ResourceManager.GetString("menu_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Windows;
        ///using System.Windows.Controls;
        ///using System.Windows.Data;
        ///using System.Windows.Documents;
        ///using System.Windows.Input;
        ///using System.Windows.Media;
        ///using System.Windows.Media.Imaging;
        ///using System.Windows.Navigation;
        ///using System.Windows.Shapes;
        ///
        ///namespace RCResourceLibs
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Логика взаимодействия для MenuStyle.xaml
        ///    /// &lt;/summar [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string menu_style_xaml {
            get {
                return ResourceManager.GetString("menu_style_xaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Offline {
            get {
                object obj = ResourceManager.GetObject("Offline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Online {
            get {
                object obj = ResourceManager.GetObject("Online", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ResourceDictionary
        /// xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///	xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///	xmlns:d=&quot;http://schemas.microsoft.com/expression/blend/2008&quot; 
        ///    xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; mc:Ignorable=&quot;d&quot;&gt;
        ///    &lt;ControlTemplate x:Key=&quot;ScrollViewerControlTemplate1&quot; TargetType=&quot;ScrollViewer&quot;&gt;
        ///        &lt;Grid x:Name=&quot;Grid&quot; Background=&quot;{TemplateBinding Background}&quot;&gt;
        ///            &lt;Grid.ColumnDefinitions&gt;
        ///             [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string scrl_vr_style {
            get {
                return ResourceManager.GetString("scrl_vr_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Windows;
        ///using System.Windows.Controls;
        ///using System.Windows.Data;
        ///using System.Windows.Documents;
        ///using System.Windows.Input;
        ///using System.Windows.Media;
        ///using System.Windows.Media.Imaging;
        ///using System.Windows.Navigation;
        ///using System.Windows.Shapes;
        ///
        ///namespace ReinCorpDesign.Styles
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Логика взаимодействия для ScrollViewerStyle.xaml
        ///  [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string scrl_vr_style_xaml {
            get {
                return ResourceManager.GetString("scrl_vr_style_xaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ResourceDictionary
        /// xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///	xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///	xmlns:d=&quot;http://schemas.microsoft.com/expression/blend/2008&quot; 
        ///    xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; mc:Ignorable=&quot;d&quot;&gt;
        ///    &lt;Style TargetType=&quot;{x:Type TabItem}&quot;&gt;
        ///            &lt;Setter Property=&quot;Foreground&quot; Value=&quot;Black&quot; /&gt;
        ///            &lt;Setter Property=&quot;Padding&quot; Value=&quot;6,1,6,1&quot; /&gt;
        ///            &lt;Setter Property=&quot;HorizontalConten [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string settings_style {
            get {
                return ResourceManager.GetString("settings_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ResourceDictionary
        ///    xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///	xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///	xmlns:d=&quot;http://schemas.microsoft.com/expression/blend/2008&quot; 
        ///    &gt;
        ///    &lt;Style x:Key=&quot;TabItemFocusVisual&quot;&gt;
        ///        &lt;Setter Property=&quot;Control.Template&quot;&gt;
        ///            &lt;Setter.Value&gt;
        ///                &lt;ControlTemplate&gt;
        ///                    &lt;Rectangle Margin=&quot;3,3,3,1&quot; SnapsToDevicePixels=&quot;true&quot; Stroke=&quot;{DynamicResource {x:Static SystemColors.ControlTextBrushKey} [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string tb_ctrl_style {
            get {
                return ResourceManager.GetString("tb_ctrl_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Windows;
        ///using System.Windows.Controls;
        ///using System.Windows.Data;
        ///using System.Windows.Documents;
        ///using System.Windows.Input;
        ///using System.Windows.Media;
        ///using System.Windows.Media.Imaging;
        ///using System.Windows.Navigation;
        ///using System.Windows.Shapes;
        ///
        ///namespace ReinCorpDesign.Styles
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Логика взаимодействия для TabControlStyle.xaml
        ///    [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string tb_ctrl_style_xaml {
            get {
                return ResourceManager.GetString("tb_ctrl_style_xaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ResourceDictionary 
        ///    xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///    xmlns:my=&quot;clr-namespace:RCResourceLibs;assembly=RCResourceLibs&quot;
        ///    &gt;
        ///    &lt;Style x:Key=&quot;TreeViewItemFocusVisual&quot;&gt;
        ///        &lt;Setter Property=&quot;Control.Template&quot;&gt;
        ///            &lt;Setter.Value&gt;
        ///                &lt;ControlTemplate&gt;
        ///                    &lt;Rectangle/&gt;
        ///                &lt;/ControlTemplate&gt;
        ///            &lt;/Setter.Value&gt;
        ///        &lt;/Setter&gt;
        ///    &lt;/Style [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string tr_v_style {
            get {
                return ResourceManager.GetString("tr_v_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Unathorized {
            get {
                object obj = ResourceManager.GetObject("Unathorized", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:my=&quot;clr-namespace:RCResourceLibs;assembly=RCResourceLibs&quot;&gt;
        ///    &lt;Style TargetType=&quot;{x:Type ContentControl}&quot;&gt;
        ///        &lt;Setter Property=&quot;Width&quot; Value=&quot;auto&quot; /&gt;
        ///        &lt;Setter Property=&quot;Height&quot; Value=&quot;auto&quot; /&gt;
        ///        &lt;Setter Property=&quot;HorizontalAlignment&quot; Value=&quot;Center&quot; /&gt;
        ///        &lt;Setter Property=&quot;VerticalAlignment&quot; V [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string win_settings {
            get {
                return ResourceManager.GetString("win_settings", resourceCulture);
            }
        }
    }
}
